# -*- coding: utf-8 -*-
"""Grupo_2_ Tarea1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_kGWIWRIiX5_DZ4iIEeDijVZqUm1PjJG
"""

#I. Utilizando un “if else” cree una estructura que evalúe “x” tal que:

x=6

if x % 2 == 0 and x % 3 == 0:
  print ("Es múltiplo de 2 y 3")
elif x % 2 == 0:
  print ("Es múltiplo de 2")
elif x % 3 == 0:
  print ("Es múltiplo de 3")
else:
  print ("Otro caso")

#II. Utilizando un “for loop” y el condicional “if else” para un rango del 1 al 100, evalúe “x”

lista = list(range(1,101))

for x in lista:
  if x % 3 == 0 and x % 5 == 0 :
    print ("FizzBuzz")
  elif x % 3 == 0:
    print ("Fizz")
  elif x % 5 == 0:
    print("Buzz")
  else:
    print(x)

#III. Crea una función 𝒄𝒂𝒍𝒄𝒖𝒍𝒂𝒓_𝒅𝒆𝒔𝒄𝒖𝒆𝒏𝒕𝒐() que permita calcular el descuento aplicado a un producto. Si el total es mayor o igual a 1000, aplica un 20% de descuento, si el total es

def calcular_descuento(precio):
  if precio >= 500 and precio < 1000:
    total = precio * 0.9
  elif precio >= 1000:
    total = precio * 0.8
  else:
    total = precio
  return total

print(calcular_descuento (1200))
print(calcular_descuento (750))
print(calcular_descuento (300))

#IV. Crea una función llamada clasificar_edad() que reciba como parámetro la edad de una persona

def clasificar_edad(edad):
  if edad < 12:
    categoria = 'Niño'
  elif edad >= 12 and edad <= 17:
    categoria = 'Adolescente'
  elif edad >= 18 and edad <= 24:
    categoria = 'Joven'
  elif edad >= 25 and edad <= 64:
    categoria = 'Adulto'
  elif edad >= 65:
    categoria = 'Adulto mayor'
  return categoria

print (clasificar_edad (10))
print (clasificar_edad (19))
print (clasificar_edad (25))
print (clasificar_edad (70))

#V. Crea una función 𝒄𝒂𝒍𝒄𝒖𝒍𝒂𝒓_𝒄𝒓𝒂𝒆𝒔𝒕(𝒎𝒆𝒅𝒊𝒂_𝒑𝒆𝒓𝒔𝒐𝒏𝒂𝒍, 𝒎𝒆𝒅𝒊𝒂_𝒄𝒖𝒓𝒔𝒐, 𝒅𝒆𝒔𝒗𝒊𝒂𝒄𝒊𝒐𝒏_𝒄𝒖𝒓𝒔𝒐)

def calcular_craest(media_personal, media_curso, desviacion_curso):
  craest = ((media_personal - media_curso) * 10)/desviacion_curso + 50
  return craest

calcular_craest (14, 15, 3.5)